---
title: 'Take home #4 - R: Analysis of the ghana_bednet dataset'
author: "Olivia Nye"
output: html_notebook
---


```{r setup}
# loading required libraries ----
library(dslabs)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(Hmisc)

```

```{r load_data} 
#readr from tidyverse instead??
df <- read_csv("ghana_bednet.csv")

class(df)
df$follyr[5743] <- 1.0
df$sex[df$sex == "1"] <- "F"
df$sex[df$sex == "0"] <- "M"
#I suggest also cleaning up one missing value, denoted as . and changing it to NA (standard R notation for missing values) as 
df$follyr[df$follyr < 0] <- NA

describe(df)

#We see your output below for answers to questions 1 & 2; however, please write-out answers in the document as well.
```

```{r}
#Question #3: proportion of male participants: 13305/26342
sexTable <- table(df$sex)
addmargins(sexTable)
round(100*prop.table(sexTable), digits = 2)

#it is great you performed your operations as part of your script (as it avoid introducing human error); do note that your proportions were also provided above after you ran your describe command
```

```{r}
#Question #4: 8395.184 years
femaleInter <- df  %>% 
             filter(sex == "F" & bednet == 1) %>%
            summarise(femaleInter = sum(follyr, na.rm = TRUE))

femaleInter
```

```{r}
#QUESTION 5: 9/370 kids in cluster 52 died

#make dataset of only kids in cluster 52
df52 <- filter(df, cluster == 52)
#view this dataset
df52
#make frequency table for outcome variable in this filtered dataset
outcomes52 <- table(df52$outcome)
#add total to table
addmargins(outcomes52)
#view frequencies as precents rounded to 2 decimal points
round(100*prop.table(outcomes52), digits = 2)
```

```{r}
#QUESTION 6
mean(df$agemn) #mean age at enrollment is 25.29 months 

sd(df$agemn) #standard deviation of enrollment age is 18.02 months

```

```{r}
#QUESTION 7 

# control group
control <- filter(df, df$bednet == 0)
#be careful as you made your above command into a comment 
control

controlDeathCount <- filter(control, control$outcome == 1) #13029 died

controlYears <- df  %>% 
             filter(bednet == 0) %>%
            summarise(controlYears = sum(follyr, na.rm = TRUE))
controlYears #--> 16493.83	years
#time contributed by participants in the non-intervention areas is correct; however there were 461 deaths (not 13029)

#controlMortRate <- 100*(controlDeathCount/controlYears) # control Death count and Control years are data.frames, which dont make sense to do arithmetic with. 

#controlMortRate #78.99% mortality rate among control group #since the above doesnt run this objet does not exist. 

#intervention group
inter <- filter(df, df$bednet == 1)
inter

interDeathCount <- length(inter$outcome == 1) # could use sum This just gives the length of logical vector for if inter$outcome == 1 wihc is the same as the length of inter$outcome
interDeathCount #13313 died

interYears <- df  %>% 
             filter(bednet == 1) %>%
            summarise(interYears = sum(follyr, na.rm = TRUE)) # this approach would have worked above. 

interYears #16841.04	years

interMortRate <- 100*(interDeathCount / interYears) 
interMortRate #79.05% mortality rate among control group 

```


```{r}
#Question 8 -- bar plot

# Grouped Bar Plot
#create count table
counts <- table(df$outcome, df$cluster)
counts
#convert 0 and 1 levels of outcome variable to text
rownames(counts)[rownames(counts) == 0] = "Survived"
rownames(counts)[rownames(counts) == 1] = "Died"

barplot(counts, main="Outcome Proportions by Cluster",
  xlab="Cluster", ylab="Number of Participants", col=c("darkblue","red"),
  legend = rownames(counts), beside=TRUE)
#you used counts but the questions asks for proportions on the y-axis
```
```{r}
#question 9 -- linlogistic regression

reg <- glm(outcome ~ bednet, family = binomial(link = 'logit'), data = df)

summary(reg)

```

#you forgot to answer question 10 which is the interpretation of the logistic regression in question 9

# no preamble per se and no output statment in YAML header.











